### PR TITLE
Consistently apply MIT OR Apache-2.0 license and clarify licence on test files

### PR DESCRIPTION
**Pull request by pixelspark**
#149 

@haixuanTao , @SludgePhD , @CameronTofer , @zimond , @aliemjay , @philpax , @maekawatoshiki please confirm you agree to dual-licensing your contributions as "MIT OR Apache-2.0" as clarified in this pull request.

### CODE REVIEW

**Comment by philpax** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by maekawatoshiki** [comment]
I allow dual-licensing my contributions as MIT OR Apache-2.0.

**Comment by haixuanTao** [comment]
OK, for both licenses MIT or APACHE as well for both past and future.

**Comment by SludgePhD** [comment]
I agree to dual-license my past & future contributions as MIT OR Apache-2.0.

**Comment by aliemjay** [comment]
I agree to license my work under MIT OR Apache-2.0

**Comment by zimond** [comment]
I agree to license my work under MIT OR Apache-2.0

**Comment by pixelspark** [comment]
OK, so that leaves @CameronTofer . Can you agree to dual-license your contribution (#139 )?

**Review by haixuanTao — APPROVED** [review]

**Comment by pixelspark** [comment]
Also @zimond and @CameronTofer still...

**Comment by pixelspark** [comment]
We are now licensed "MIT OR Apache-2.0" ! Thanks all for the replies.

@CameronTofer unfortunately I had to remove your contribution for now. Creating certainty about the licensing situation is in the best interest of the project. If you agree to relicense your contributions we can simply merge it back (I prepared a PR: #152).

**Comment by antimora** [comment]
@pixelspark Awesome! Thank you for the clarification. 

We would like to use your code in the [Burn project](https://github.com/burn-rs/burn) as a [`burn-wgpu` backend](https://github.com/burn-rs/burn/issues/243). Currently, Burn has two backends (torch and ndarray). The `burn-wgpu` backend will allow accessing GPU on my many platforms without the need to install torch. This is great for training and inference. Also, `burn-wgpu` will allow acceleration on the web. Just recently we published an [example running MNIST inference](https://github.com/burn-rs/burn/tree/main/examples/mnist-inference-web) on the web using wasm. You can try the [live demo](https://burn-rs.github.io/demo). So if we have a `burn-wgpu` backend, it will be easy just to swap the burn-ndarray backend with `burn-wgpu`, to have GPU acceleration on the web.

(I am tagging @nathanielsimard here so he's aware of this ticket. He's the creator and developer of Burn. He was also excited about the possibility to run train/inference on AMD GPUs).

**Pull request merged**
